<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MySocialWidgets\Module'                            => __DIR__ . '/src/Module.php',
  'MySocialWidgets\View\Helper\AbstractHelperFactory' => __DIR__ . '/src/View/Helper/AbstractHelperFactory.php',
  'MySocialWidgets\View\Helper\AbstractHelper'        => __DIR__ . '/src/View/Helper/AbstractHelper.php',
  'MySocialWidgets\View\Helper\FacebookPageEvents'    => __DIR__ . '/src/View/Helper/FacebookPageEvents.php',
  'MySocialWidgets\Client\AbstractClientFactory'      => __DIR__ . '/src/Client/AbstractClientFactory.php',
  'MySocialWidgets\Client\ClientException'            => __DIR__ . '/src/Client/ClientException.php',
  'MySocialWidgets\Options\HelperOptions'             => __DIR__ . '/src/Options/HelperOptions.php',
  'MySocialWidgets\Options\ModuleOptionsFactory'      => __DIR__ . '/src/Options/ModuleOptionsFactory.php',
  'MySocialWidgets\Options\ModuleOptions'             => __DIR__ . '/src/Options/ModuleOptions.php',
);
