<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MySocialWidgets\Exception\ClientException'         => __DIR__ . '/src/MySocialWidgets/Exception/ClientException.php',
  'MySocialWidgets\Factory\ClientAbstractFactory'     => __DIR__ . '/src/MySocialWidgets/Factory/ClientAbstractFactory.php',
  'MySocialWidgets\Factory\CacheAdapterFactory'       => __DIR__ . '/src/MySocialWidgets/Factory/CacheAdapterFactory.php',
  'MySocialWidgets\Factory\ViewHelperAbstractFactory' => __DIR__ . '/src/MySocialWidgets/Factory/ViewHelperAbstractFactory.php',
  'MySocialWidgets\Module'                            => __DIR__ . '/src/MySocialWidgets/Module.php',
  'MySocialWidgets\View\Helper\AbstractSocialHelper'  => __DIR__ . '/src/MySocialWidgets/View/Helper/AbstractSocialHelper.php',
  'MySocialWidgets\View\Helper\FacebookPageEvents'    => __DIR__ . '/src/MySocialWidgets/View/Helper/FacebookPageEvents.php',
  'MySocialWidgets\View\Helper\InstagramGallery'      => __DIR__ . '/src/MySocialWidgets/View/Helper/InstagramGallery.php',
);
